// Generate illustrated Markdown user manuals from a tour + the screenshots
// captured by the Playwright run. One manual per language present in the
// export's i18n maps; screenshots are shared across languages.
import fs from "node:fs";
import path from "node:path";
import { tr } from "./loadTours.mjs";
import { shotFile, shotDir } from "./names.mjs";

const LANG_NAMES = {
  en_US: "English",
  si_LK: "සිංහල (Sinhala)",
  ta_IN: "தமிழ் (Tamil)",
};

// Human-readable hint per validation type, for the manual.
const VALIDATION_HINT = {
  required: "This field is required.",
  integer: "Enter a whole number.",
  float: "Enter a number (decimals allowed).",
  email: "Enter a valid email address.",
  phone: "Enter a valid phone number.",
  url: "Enter a valid URL.",
  date: "Enter a valid date.",
  alpha: "Letters only.",
  alphanumeric: "Letters and numbers only.",
  regex: "Enter a value in the expected format.",
};

function langName(code) {
  return LANG_NAMES[code] || code;
}

/**
 * @param {object} tour normalized tour
 * @returns {Array<{filename:string, content:string, lang:string}>}
 */
export function genManuals(tour) {
  const total = tour.steps.length;
  const dir = shotDir(tour.slug); // relative to tool root, posix
  // Manuals live in generated/manuals/; screenshots in generated/screenshots/.
  // Relative path from a manual file to a screenshot: ../screenshots/<slug>/…
  const relDir = path.posix.join("..", "screenshots", tour.slug);

  return tour.langs.map((lang) => {
    const out = [];
    const title = tr(tour.name, tour.name_i18n, lang);
    const desc = tr(tour.description, tour.description_i18n, lang);

    out.push(`# ${title}`);
    out.push("");
    out.push(`_User manual · ${langName(lang)} · ${total} step${total === 1 ? "" : "s"}_`);
    out.push("");
    if (desc) {
      out.push(desc);
      out.push("");
    }
    out.push("---");
    out.push("");

    for (const step of tour.steps) {
      const stepTitle = tr(step.title, step.title_i18n, lang) || `Step ${step.number}`;
      const stepContent = tr(step.content, step.content_i18n, lang);
      const file = shotFile(step.number, total);
      const shotPath = path.join(dir, file);
      const rel = path.posix.join(relDir, file);

      out.push(`## ${step.number}. ${stepTitle}`);
      out.push("");
      if (stepContent) {
        out.push(stepContent);
        out.push("");
      }
      if (step.validation_type && step.validation_type !== "none") {
        const vmsg =
          tr(step.validation_message, step.validation_message_i18n, lang) ||
          VALIDATION_HINT[step.validation_type] ||
          "";
        if (vmsg) {
          out.push(`> ℹ️ ${vmsg}`);
          out.push("");
        }
      }
      if (fs.existsSync(shotPath)) {
        out.push(`![${stepTitle}](${rel})`);
      } else {
        out.push(`_(screenshot pending — run \`npm test\` to capture \`${rel}\`)_`);
      }
      out.push("");
    }

    out.push("---");
    out.push("");
    out.push(`_Generated by tour2playwright from a Tour Recorder export._`);
    out.push("");

    return {
      lang,
      filename: `${tour.slug}.${lang}.md`,
      content: out.join("\n"),
    };
  });
}
